# Generated by Django 5.0 on 2024-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('gbjoy', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='img/')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
